openapi: 3.0.1

info:
  title: Balance application - Swagger 3.0
  version: 1.0.0
servers:
  - url: http://localhost:9090
tags:
  - name: Health
    description: Методы для проверки работоспособности
  - name: Пользователи
    description: Методы для работы с пользователем
  - name: Счета
    description: Методы для работы со счетами
  - name: Услуги
    description: Методы для работы с услугами
  - name: Бухгалтерия
    description: Методы для работы с бухгалтерией
  - name: Транзакции
    description: Методы для работы с транзакциями
paths:
  /health:
    get:
      tags:
        - Health
      summary: Получить статус приложения
      responses:
        '200':
          description: Статус приложения и время
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
  /users/{userId}:
    get:
      tags:
        - Пользователи
      summary: Получить баланс пользователя
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID пользователя
      responses:
        '200':
          description: Баланс пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/deposit:
    post:
      tags:
        - Пользователи
      summary: Зачислить средства на баланс
      responses:
        '200':
          description: JSON пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                deposit:
                  type: number

  /accounting:
    get:
      tags:
        - Бухгалтерия
      summary: Получить записи бухгалтерии
      responses:
        '200':
          description: Записи бухгалтерии
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Accounting'
  /accounting/csv:
    get:
      tags:
        - Бухгалтерия
      summary: Экспорт записей за месяц в csv
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            minimum: 1
          description: дата в формате yyyy-MM
      responses:
        '200':
          description: Загрузка CSV файла должна начаться
  /services/{serviceId}:
    get:
      tags:
        - Услуги
      summary: Получить услугу по айди
      parameters:
        - in: path
          name: serviceId
          required: true
          schema:
            type: integer
            minimum: 1
          description: Айди услуги
      responses:
        '200':
          description: Услуга
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
  /bills:
    post:
      tags:
        - Счета
      summary: Резервирование средств
      responses:
        '200':
          description: Счет
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                serviceId:
                  type: integer
                orderId:
                  type: integer
                price:
                  type: number
  /bills/{billId}/approve:
    patch:
      tags:
        - Счета
      summary: Подтвердить резервирование и зачислить деньги на счет компании
      parameters:
        - in: path
          name: billId
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID счета
      responses:
        '200':
          description: Счет
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
  /bills/{billId}/reject:
    patch:
      tags:
        - Счета
      summary: Отменить резервирование и зачислить деньги обратно пользователю
      parameters:
        - in: path
          name: billId
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID счета
      responses:
        '200':
          description: Счет
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
  /transactions:
    get:
      tags:
        - Транзакции
      summary: Получить транзакции пользователя
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID пользователя
        - in: query
          name: page
          required: true
          schema:
            type: integer
            default: 0
            minimum: 1
          description: номер страницы (0,1,...,N)
        - in: query
          name: size
          required: true
          schema:
            type: integer
            default: 10
            minimum: 1
          description: количество элементов на странице (2,3,...,N)
        - in: query
          name: sort
          required: true
          schema:
            type: string
            default: date
            minimum: 1
          description: сортировка по полю (date\price)
        - in: query
          name: dir
          required: true
          schema:
            type: string
            default: asc
            minimum: 1
          description: порядок сортировки (asc\desc)
      responses:
        '200':
          description: Список транзакций пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'



components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        balance:
          type: integer
    Service:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Bill:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        service:
          $ref: '#/components/schemas/Service'
        orderId:
          type: integer
        price:
          type: integer
        status:
          type: string
          enum:
            - PENDING
            - REJECT
            - APPROVE
        moderateAt:
          type: string
    Accounting:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        service:
          $ref: '#/components/schemas/Service'
        orderId:
          type: integer
        price:
          type: integer
        createdAt:
          type: string
    Transaction:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        price:
          type: integer
        comment:
          type: string
        status:
          type: string
          enum:
            - PAYMENT
            - DEPOSIT
            - RESERVED
        date:
          type: string
    Health:
      type: object
      properties:
        status:
          type: string
        time:
          type: string
